# Generated by Django 4.1.4 on 2022-12-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yoga_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerusermodel",
            name="age",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="registerusermodel",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
