# Generated by Django 4.1.4 on 2022-12-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yoga_api", "0002_alter_registerusermodel_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registerusermodel",
            name="id",
        ),
        migrations.AlterField(
            model_name="registerusermodel",
            name="email",
            field=models.EmailField(
                db_index=True,
                max_length=254,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
